import * as allfunctions from "./modules/functions.js";

allfunctions.viewFixedHeader();
allfunctions.reviewsSlider();
allfunctions.newsSlider();
allfunctions.showFeedbackModal();
allfunctions.tabProducts();
allfunctions.footerSpoilerNav();
allfunctions.portfolioSlider();
allfunctions.advantagesMobileSlider();
allfunctions.mobileMenu();
allfunctions.dropSearchPanel();
allfunctions.spoilerSidebarItem();
allfunctions.rangeSlider();
allfunctions.sortCatalog();
allfunctions.previewProductSlider();
allfunctions.cardProductTabs();
allfunctions.productMobileSpoiler();
allfunctions.similarProductsSlider();
allfunctions.reviewTab();
allfunctions.popularServicesSlider();
allfunctions.employeesSlider();
allfunctions.openMobileFilterCatalog();